# Generated by Django 2.1.1 on 2018-09-17 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Budget_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='titile',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='Budget_App.Plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
